
version: "3.9"
services:
  flaskcloude:
    image: "flaskcloude:latest"
    ports:
      - "5000:5000"
    links:
      - authenication
      - doctor
    deploy:
      replicas: 1
  doctor:
    image: "sajadkh/doctor_system_doctor_panel"
    ports:
      - "5001:8001"
    deploy:
      replicas: 1
  patient:
    image: "sajadkh/doctor_system_patient_panel"
    links:
      - doctor
    ports:
      - "5002:8002"
    deploy:
      replicas: 1
  authenication:
    image: "sajadkh/doctor_system_authentication"
    ports:
      - "5003:8000"
    deploy:
      replicas: 2
  



#   mariadb:
#       container_name: mariadb
#           # let's grab from mysql 5.7 image
#       image: mariadb
#       volumes:
#               # pass volume named mysql-data to mysql container
#             # - mysql-data:/var/lib/mysql
#       restart: unless-stopped
#       labels:
#       project: "flask"
#       day: "9 Sep 2019"
#           # ports:
#           #   - "3306:3306"
#       environment:
#             # credentials
#       MYSQL_ALLOW_EMPTY_PASSWORD: yes
#       MYSQL_DATABASE: cloude
#       MYSQL_USER: user
#       MYSQL_PASSWORD: 123456
      